### ISSUE TITLE
Dockerfile for web application doesn't seem to work. 

### ISSUE THREAD

**Issue by KevinBurton** [iolevel/peachpie-samples#1]
I do 

docker build -t tag .

then do

docker run tag

and I get

  Restore completed in 39.48 ms for /wwwroot/app/app.csproj.
  Restore completed in 18.04 ms for /wwwroot/website/website.msbuildproj.
  Restore completed in 27.08 ms for /wwwroot/website/website.msbuildproj.
No executable found matching command "dotnet-watch"

**Comment by KevinBurton** [comment]
I am not sure why this was closed?

**Comment by jakubmisek** [comment]
@KevinBurton the issue was fixed in https://github.com/iolevel/peachpie-samples/commit/d730a34ded598cc3ee3957fbc454f686760aae96
There was a missing dependency to `dotnet-watch` cli tool
