### ISSUE TITLE
Not an issue. But MAN is this a cool project

### ISSUE THREAD

**Issue by ensemblebd** [iolevel/peachpie-samples#2]
I figured I'd google search just to see what's out there. What a gem!
Not sure how well it would work with plugins that use weird systems like eval(), unless the php binary is embedded into that compiled output (wordfence for instance). 

Very cool. I shall investigate further.
Feel free to close this, good day to you

**Comment by jakubmisek** [comment]
haha thanks! and `eval()` is supported
