### ISSUE TITLE
Project file is incomplete. Expected imports are missing

### ISSUE THREAD

**Issue by gordon-matt** [iolevel/peachpie-samples#3]
Using **VS 2017** and trying to test the samples. Have tried both the **web-application** and **csharp-php-hybrid** apps, but both of them give the following error when opened:

**"Project file is incomplete. Expected imports are missing"**

Do I need to install something first or what am I missing here?

**Comment by jakubmisek** [comment]
It should work (and works on my environment) out of the box.

Ensure you have updated VS to latest 15.5.7. Running `dotnet restore` on commandline before opening the solution might help.

**Comment by gordon-matt** [comment]
I've just updated VS and it still had the same error. I then tried `dotnet restore` and that seems to have fixed it, thanks.

**Comment by hexarcate** [comment]
Experiencing the same issue. VS2017 v15.7.0. dotnet restore completed successfully but not luck. Here's my msbuildproj file:

**Comment by jakubmisek** [comment]
@hexarcate works for me, try our official samples on https://github.com/iolevel/peachpie-samples/tree/master/console-application

**Comment by eloekset** [comment]
I also got this error message on a project I was working on a few weeks ago. Found that VS2017 15.7.6 didn't recognize my .NET Core 2.1.203 SDK (x64) - I couldn't see it in the target framework drop down - so I uninstalled all .NET Core SDKs from 1.X and up, and reinstalled 2.1.203 SDK. Reopened VS2017, and it loaded the project just fine.

**Comment by DaveMagrathSmith** [comment]
I'm getting the same error when trying to open PeachPie libraries in Visual Studio 2017 (15.8.2):  "Project file is incomplete.  Expected imports are missing".  This happens even with the official 'php-library' sample.

This is my dotnet --info:

`
.NET Core SDK (reflecting any global.json):
 Version:   2.1.401
 Commit:    91b1c13032

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.401\

Host (useful for support):
  Version: 2.1.3
  Commit:  124038c13e

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program `Files\dotnet\shared\Microsoft.NETCore.App]
`

And here is the sample msbuildproj file:

`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Globals">
    <ProjectGuid>df336813-58ea-4ede-a1eb-ad8e4fa7b0dd</ProjectGuid>
  </PropertyGroup>
  <PropertyGroup>
    <OutputType>library</OutputType>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Version>0.0.1-preview</Version>
    <AssemblyOriginatorKeyFile>..\mykey.snk</AssemblyOriginatorKeyFile> 
    <SignAssembly>true</SignAssembly> 
    <PublicSign Condition="'$(OS)' != 'Windows_NT'">true</PublicSign>
    <GenerateDocumentation>true</GenerateDocumentation>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="**/*.php" />
    <Content Include="**/*.map" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Peachpie.Compiler.Tools" Version="0.9.0-*" />
    <PackageReference Include="Peachpie.NET.Sdk" Version="0.9.0-*" PrivateAssets="Build" />
    <PackageReference Include="Peachpie.Library.Graphics" Version="0.9.0-*"/>
  </ItemGroup>
</Project>`


I am able to create C# libraries targeting .NET Standard 2.0 without problem.  Any thoughts?

**Comment by jakubmisek** [comment]
@DaveMagrathSmith you have to run `dotnet restore` once before opening in VS2017. More at https://docs.peachpie.io/get-started/#visual-studio

**Comment by DaveMagrathSmith** [comment]
Thanks, Jakub.  I had forgotten to run dotnet restore on the sample application, and that did fix the problem there.

However, I am still unable to open new projects created locally.  For example:

C:\Projects\PHPLibTest>dotnet new classlib -lang PHP
The template "Class library" was created successfully.

C:\Projects\PHPLibTest>dotnet restore
  Restoring packages for C:\Projects\PHPLibTest\PHPLibTest.msbuildproj...
  Restoring packages for C:\Projects\PHPLibTest\PHPLibTest.msbuildproj...
  Installing Peachpie.CodeAnalysis 0.9.0-CI01110.
  Installing Peachpie.Compiler.Tools 0.9.0-CI01110.
  Restore completed in 1.27 sec for C:\Projects\PHPLibTest\PHPLibTest.msbuildproj.
  Installing Peachpie.Library 0.9.0-CI01110.
  Installing Peachpie.Runtime 0.9.0-CI01110.
  Installing Peachpie.Library.XmlDom 0.9.0-CI01110.
  Installing Peachpie.Library.Scripting 0.9.0-CI01110.
  Installing Peachpie.Library.MsSql 0.9.0-CI01110.
  Installing Peachpie.Library.MySql 0.9.0-CI01110.
  Installing Peachpie.Library.Network 0.9.0-CI01110.
  Installing Peachpie.Library.PDO 0.9.0-CI01110.
  Installing Peachpie.App 0.9.0-CI01110.
  Installing Peachpie.NET.Sdk 0.9.0-CI01110.
  Generating MSBuild file C:\Projects\PHPLibTest\obj\PHPLibTest.msbuildproj.nuget.g.props.
  Generating MSBuild file C:\Projects\PHPLibTest\obj\PHPLibTest.msbuildproj.nuget.g.targets.
  Restore completed in 2.29 sec for C:\Projects\PHPLibTest\PHPLibTest.msbuildproj.

Everything looks good, but when I try to open in visual studio, I get the "Project file is incomplete. Expected imports are missing" error.  I wonder if there is something wrong with the template?  Having trouble figuring out what could be going wrong, but I'll keep digging...

**Comment by DaveMagrathSmith** [comment]
I figured it out.  The Class Library template creates a project file with a `<TargetFrameworks>` (plural) element.  If I change it to `<TargetFramework>` (singular), and run a dotnet restore, the project opens successfully.

**Comment by jakubmisek** [comment]
Thanks @DaveMagrathSmith we'll try.

For now the recommended IDE is VSCode, we haven't implemented full support for VS yet. Btw I've noticed your `dotnet restore` seems to did `Restoring packages` twice ... maybe you run it twice resulting in an invalid /obj.

**Comment by HEBOS** [comment]
Check global.json in your solution folder. It should state the version of the .NET Core SDK.
A compatible (same or newer) version should be installed. 
Make sure it is **x86** version, though.

**Comment by JeremyWard33** [comment]
Got the same error in VS2017.  Uninstalled the latest version of .NET Core and the project then opened without error.  I now appear to have .NET Core SDK 1.1.0, 2.1.2 and 2.1.202, all x64.  The offending product was Microsoft .NET Core SDK 2.2.204 (x64).

**Comment by ntinsley78** [comment]
So my case was just a bit different, adding this solution for anyone else whom may have done what I did.

I was getting this error when opening up an older solutions in VS 2017.  In my case I had installed VS 2019 preview and .NET Core 3 preview, and was running the two versions in parallel.  To resolve my issue all I had to do was run the project in VS 2019 instead of VS 2017, something was updated when I installed the newer versions of VS and .NET Core.

**Comment by fejango** [comment]
I just solved the problem with deleting the global.json file.

**Comment by Stoyas** [comment]
Got the same issue for project built with .net core 2.2, just installed the latest stable version and it worked.

**Comment by aaronasmith** [comment]
I had this issue because I had a global.json file.  When I deleted that file my project loaded fine.

**Comment by vijaysahu12** [comment]
After trying all possible solution I got frustrated then I delete the global.json file and it fixed my solution too.. Thanks for your help guys

**Comment by sebainones** [comment]
> So my case was just a bit different, adding this solution for anyone else whom may have done what I did.
> 
> I was getting this error when opening up an older solutions in VS 2017. In my case I had installed VS 2019 preview and .NET Core 3 preview, and was running the two versions in parallel. To resolve my issue all I had to do was run the project in VS 2019 instead of VS 2017, something was updated when I installed the newer versions of VS and .NET Core.

The same scenario@ntinsley78 and the same solution. Anyways, It would be useful to know what have changed or what can we do as I need to open the project from VS 2019 but as well from VS 2017.

**Comment by jakubmisek** [comment]
The project uses Sdk which is hosted on [nuget.org/packages/peachpie.net.sdk](https://www.nuget.org/packages/peachpie.net.sdk). The ability to download Sdk from remote sources has been introduced in **Visual Studio 2017 Update 6** (version 15.6). I'm not sure if you should also enable the option to download missing packages automatically:
![image](https://user-images.githubusercontent.com/842150/75035655-4792c600-54b0-11ea-99e1-931ab6d900db.png)

If Visual Studio fails to download and/or open the project, run following command:
```
dotnet restore
```
Which also downloads and restores all the necessary project dependencies, including the Sdk reference.

**Comment by sebainones** [comment]
I have VS 2017 (Version 15.8.7) . Also,  in Option->Nuget Package Manager -> General I Have already that enabled.  Either that or doing "dotnet restore" unfortunately solves my issue. As @ntinsley78 mentioned the only way (I've found so far) it's to open it with VS 2019. Before installing 2019 I had no issues with that project being open in VS 2017.

**Comment by jakubmisek** [comment]
@sebainones oh, that's interesting ... like that Sdk Resolver bundled with VS2019 breaks this feature in VS2017 .. I'll try that soon and look for similar issues on dotnet forums.

FYI this is the feature that we're using https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk?view=vs-2019#how-project-sdks-are-resolved

**Comment by galanar** [comment]
@jakubmisek I came up to this issue just some minutes ago after updating VS 2019 to the latest version.
Before, I was able to open my solution in VS 2017 and now I am getting this issue.
As I have only a commercial license for VS 2017 (company) and using the VS 2019 for private use and testing, any suggestions what I can do now?

**Comment by jakubmisek** [comment]
@galanar 
run 
```
dotnet restore
```
 on commandline if anything like this happens.

License or edition of VS makes no difference. The project file is supported in general on VS 2017 (version 15 Update 6 and newer, which is a few years update already)

**Comment by ajnicolay** [comment]
Deleting the global.json file worked for me!

**Comment by Slion** [comment]
Nothing to do with that project but in my case I was missing a VS2017 installation package named ".NET Core runtime".
After installing it through Visual Studio Installer everything worked.
